name: Deploy Honkit to GitHub Pages

on:
  push:
    branches:
      - main

# 添加权限设置
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Install Honkit
      run: npm install honkit --save-dev

    - name: Remove PDF and EPUB files
      run: |
        rm -f *.pdf
        rm -f *.epub

    - name: Build Honkit
      run: npx honkit build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_book